<?php

namespace Database\Seeders;

use App\Models\Comercio;
use App\Models\Grupo;
use Illuminate\Database\Seeder;

class GrupoYComercioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $gruposData = [
            [
                'nombre' => 'ESCIFOR',
                'slug' => 'escifor',
                'descripcion' => 'Grupo especializado en formación técnica y profesional ESCIFOR.',
                'activo' => true,
                'comercios' => [
                    [
                        'nombre' => 'ISTP SIS',
                        'slug' => 'istp-sis',
                        'codigo' => 'SIS',
                        'sigla' => 'CEI',
                        'color_hex' => '#0c43a3',
                        'certificado_url' => 'https://istpsis.edu.pe/docs/certificado.pdf',
                        'resolucion_revalidacion' => 'https://istpsis.edu.pe/docs/resolucion-revalidacion-632-2006-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/',
                        'malla_curricular_url' => 'https://istpsis.edu.pe/docs/malla-curricular-brochure-2022-2023.pdf',
                        'plataforma_carrera' => 'https://aula.istpsis.edu.pe',
                        'pagina_web' => 'https://istpsis.edu.pe',
                        'resolucion_creacion' => 'https://istpsis.edu.pe/docs/resolucion-creacion-355-97-ed.pdf',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0458921',
                        'reconocimiento_director' => 'https://istpsis.edu.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://istpsis.edu.pe/seminarios',
                        'canales_youtube' => [
                            'https://youtube.com/watch?v=sis-yt1',
                            'https://youtube.com/watch?v=sis-yt2',
                            'https://youtube.com/watch?v=sis-yt3',
                        ],
                        'convenio' => 'https://istpsis.edu.pe/docs/convenio.pdf',
                        'fotos' => [
                            'https://istpsis.edu.pe/img/foto1.jpg',
                            'https://istpsis.edu.pe/img/foto2.jpg',
                        ],
                        'descripcion' => 'Instituto Superior Tecnológico Privado SIS (CEI)',
                    ],
                    [
                        'nombre' => 'ISTP AVANTI',
                        'slug' => 'istp-avanti',
                        'codigo' => 'AVANTI',
                        'sigla' => 'AVANTI',
                        'color_hex' => '#dc2626',
                        'catalogo_url' => 'https://avanti.edu.pe/catalogo-avanti-2026.pdf',
                        'reconocimiento_director' => 'https://avanti.edu.pe/reconocimiento-director.pdf',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/',
                        'plataforma_carrera' => 'https://avanti.edu.pe/plataforma',
                        'pagina_web' => 'https://avanti.edu.pe',
                        'como_ingresar_plataforma' => 'https://youtube.com/watch?v=avanti-tutorial',
                        'promocion_vigente' => null,
                        'certificado_url' => 'https://institutoavanti.edu.pe/docs/certificado.pdf',
                        'resolucion_revalidacion' => 'https://institutoavanti.edu.pe/docs/resolucion-revalidacion-415-2010-ed.pdf',
                        'resolucion_creacion' => 'https://institutoavanti.edu.pe/docs/resolucion-creacion-280-99-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod=0562143',
                        'malla_curricular_url' => 'https://institutoavanti.edu.pe/malla-curricular-avanti.pdf',
                        'seminario' => 'https://institutoavanti.edu.pe/masterclass-liderazgo',
                        'convenio' => 'Alianza Estratégica con Red Latinoamericana de Negocios.',
                        'canales_youtube' => ['https://youtube.com/watch?v=avanti-tutorial'],
                        'fotos' => ['https://images.unsplash.com/photo-1524178232363-1fb2b075b655'],
                        'descripcion' => 'Instituto Superior Tecnológico Privado AVANTI',
                        'custom_attributes' => [
                            'catalogo_label' => 'Catálogo AVANTI 2026',
                            'reconocimiento_label' => 'Reconocimiento',
                            'escale_label' => 'ESCALE',
                            'plataforma_label' => 'PlataformaWeb',
                            'pagina_label' => 'PaginaWeb',
                            'tutorial_label' => 'Youtube',
                            'promocion_label' => null,
                        ],
                    ],
                    [
                        'nombre' => 'NEXT-ONLINE',
                        'slug' => 'next-online',
                        'codigo' => 'NEXT',
                        'sigla' => 'NXT',
                        'color_hex' => '#78350f',
                        'pagina_web' => 'https://nextonline.pe',
                        'plataforma_carrera' => 'https://app.nextonline.pe',
                        'certificado_url' => 'https://nextonline.pe/certificacion-digital.pdf',
                        'resolucion_revalidacion' => 'https://nextonline.pe/docs/resolucion-revalidacion-108-2020-minedu.pdf',
                        'resolucion_creacion' => 'https://nextonline.pe/docs/resolucion-creacion-52-2018-minedu.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0789123',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0789123',
                        'malla_curricular_url' => 'https://nextonline.pe/malla-fullstack.pdf',
                        'reconocimiento_director' => 'https://nextonline.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://nextonline.pe/bootcamps-ia',
                        'convenio' => 'Convenio con empresas de tecnología y startups de software.',
                        'canales_youtube' => ['https://youtube.com/@nextonline-tech', 'https://youtube.com/@next-tutorials'],
                        'fotos' => ['https://images.unsplash.com/photo-1531482615713-2afd69097998'],
                        'descripcion' => 'Plataforma de formación continua y especialización NEXT-ONLINE',
                    ],
                    [
                        'nombre' => 'MAGISTER',
                        'slug' => 'magister',
                        'codigo' => 'MAG',
                        'sigla' => 'MAG',
                        'color_hex' => '#3b82f6',
                        'pagina_web' => 'https://magister.edu.pe',
                        'plataforma_carrera' => 'https://virtual.magister.edu.pe',
                        'certificado_url' => 'https://magister.edu.pe/docs/acreditacion.pdf',
                        'resolucion_revalidacion' => 'https://magister.edu.pe/docs/resolucion-revalidacion-889-2015-ed.pdf',
                        'resolucion_creacion' => 'https://magister.edu.pe/docs/resolucion-creacion-120-2004-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0623910',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0623910',
                        'malla_curricular_url' => 'https://magister.edu.pe/malla-posgrados.pdf',
                        'reconocimiento_director' => 'https://magister.edu.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://magister.edu.pe/conferencias-gestion-publica',
                        'convenio' => 'Convenio con Escuela Nacional de Administración Pública.',
                        'canales_youtube' => ['https://youtube.com/@magister-posgrados'],
                        'fotos' => [],
                        'descripcion' => 'Centro de alta especialización y postgrados MAGISTER',
                    ],
                ],
            ],
            [
                'nombre' => 'MULTIMARCA',
                'slug' => 'multimarca',
                'descripcion' => 'Línea de formación técnica multimarca y seguridad industrial.',
                'activo' => true,
                'comercios' => [
                    [
                        'nombre' => 'CECAVA',
                        'slug' => 'cecava',
                        'codigo' => 'CECAVA',
                        'sigla' => 'CEC',
                        'color_hex' => '#16a34a',
                        'pagina_web' => 'https://cecava.pe',
                        'plataforma_carrera' => 'https://aula.cecava.pe',
                        'certificado_url' => 'https://cecava.pe/docs/certificado-tecnico.pdf',
                        'resolucion_revalidacion' => 'https://cecava.pe/docs/resolucion-revalidacion-230-2014-ed.pdf',
                        'resolucion_creacion' => 'https://cecava.pe/docs/resolucion-creacion-741-2002-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0384192',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0384192',
                        'malla_curricular_url' => 'https://cecava.pe/malla-maquinaria.pdf',
                        'reconocimiento_director' => 'https://cecava.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://cecava.pe/talleres-mantenimiento',
                        'convenio' => 'Convenio con principales empresas del sector construcción.',
                        'canales_youtube' => ['https://youtube.com/@cecava-maquinaria'],
                        'fotos' => [],
                        'descripcion' => 'Centro de Capacitación y Valoración CECAVA',
                    ],
                    [
                        'nombre' => 'CECAVA-MIN',
                        'slug' => 'cecava-min',
                        'codigo' => 'CECAVA-MIN',
                        'sigla' => 'CMIN',
                        'color_hex' => '#ca8a04',
                        'pagina_web' => 'https://cecava-min.pe',
                        'plataforma_carrera' => 'https://campus.cecava-min.pe',
                        'certificado_url' => 'https://cecava-min.pe/certificacion-minera.pdf',
                        'resolucion_revalidacion' => 'https://cecava-min.pe/docs/resolucion-revalidacion-512-2017-minem.pdf',
                        'resolucion_creacion' => 'https://cecava-min.pe/docs/resolucion-creacion-180-2011-minem.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0492104',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0492104',
                        'malla_curricular_url' => 'https://cecava-min.pe/malla-mineria.pdf',
                        'reconocimiento_director' => 'https://cecava-min.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://cecava-min.pe/congreso-seguridad-minera',
                        'convenio' => 'Convenio con Instituto de Ingenieros de Minas del Perú.',
                        'canales_youtube' => ['https://youtube.com/@cecava-mineria'],
                        'fotos' => [],
                        'descripcion' => 'Especialización en Minería y Maquinaria Pesada CECAVA-MIN',
                    ],
                    [
                        'nombre' => 'MATPEL',
                        'slug' => 'matpel',
                        'codigo' => 'MATPEL',
                        'sigla' => 'MAT',
                        'color_hex' => '#ea580c',
                        'pagina_web' => 'https://matpel.pe',
                        'plataforma_carrera' => 'https://aula.matpel.pe',
                        'certificado_url' => 'https://matpel.pe/docs/cert-matpel.pdf',
                        'resolucion_revalidacion' => 'https://matpel.pe/docs/resolucion-revalidacion-140-2018-osinergmin.pdf',
                        'resolucion_creacion' => 'https://matpel.pe/docs/resolucion-creacion-95-2013-indeci.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0581923',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0581923',
                        'malla_curricular_url' => 'https://matpel.pe/malla-matpel.pdf',
                        'reconocimiento_director' => 'https://matpel.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://matpel.pe/simulacros-emergencia',
                        'convenio' => 'Acreditación con normas internacionales NFPA y OSHA.',
                        'canales_youtube' => ['https://youtube.com/@matpel-seguridad'],
                        'fotos' => [],
                        'descripcion' => 'Manejo de Materiales Peligrosos y Seguridad MATPEL',
                    ],
                ],
            ],
            [
                'nombre' => 'GLOBALEX',
                'slug' => 'globalex',
                'descripcion' => 'Formación global y carreras de alta demanda GLOBALEX.',
                'activo' => true,
                'comercios' => [
                    [
                        'nombre' => 'ISTP GLOBALEX',
                        'slug' => 'istp-globalex',
                        'codigo' => 'GLOBALEX',
                        'sigla' => 'GLO',
                        'color_hex' => '#0284c7',
                        'pagina_web' => 'https://globalex.edu.pe',
                        'plataforma_carrera' => 'https://virtual.globalex.edu.pe',
                        'certificado_url' => 'https://globalex.edu.pe/docs/certificado.pdf',
                        'resolucion_revalidacion' => 'https://globalex.edu.pe/docs/resolucion-revalidacion-780-2016-ed.pdf',
                        'resolucion_creacion' => 'https://globalex.edu.pe/docs/resolucion-creacion-440-2005-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0681940',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0681940',
                        'malla_curricular_url' => 'https://globalex.edu.pe/malla-comercio-exterior.pdf',
                        'reconocimiento_director' => 'https://globalex.edu.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://globalex.edu.pe/foros-aduanas',
                        'convenio' => 'Convenio con Asociación de Exportadores (ADEX).',
                        'canales_youtube' => ['https://youtube.com/@globalex-edu'],
                        'fotos' => [],
                        'descripcion' => 'Instituto Superior Tecnológico Privado GLOBALEX',
                    ],
                ],
            ],
            [
                'nombre' => 'IGE',
                'slug' => 'ige',
                'descripcion' => 'Instituto de Gestión y Especialización IGE.',
                'activo' => true,
                'comercios' => [
                    [
                        'nombre' => 'ISTP IGE',
                        'slug' => 'istp-ige',
                        'codigo' => 'IGE',
                        'sigla' => 'IGE',
                        'color_hex' => '#d97706',
                        'pagina_web' => 'https://institutoige.edu.pe',
                        'plataforma_carrera' => 'https://campus.institutoige.edu.pe',
                        'certificado_url' => 'https://institutoige.edu.pe/docs/certificado-ige.pdf',
                        'resolucion_revalidacion' => 'https://institutoige.edu.pe/docs/resolucion-revalidacion-690-2015-ed.pdf',
                        'resolucion_creacion' => 'https://institutoige.edu.pe/docs/resolucion-creacion-312-2001-ed.pdf',
                        'escale_minedu' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0719402',
                        'link_directo_escale' => 'https://escale.minedu.gob.pe/padron-ce?cod_mod=0719402',
                        'malla_curricular_url' => 'https://institutoige.edu.pe/malla-gestion.pdf',
                        'reconocimiento_director' => 'https://institutoige.edu.pe/docs/reconocimiento-director.pdf',
                        'seminario' => 'https://institutoige.edu.pe/webinars-rrhh',
                        'convenio' => 'Convenio con Colegios Profesionales y Red de Gestión Empresarial.',
                        'canales_youtube' => ['https://youtube.com/@institutoige'],
                        'fotos' => [],
                        'descripcion' => 'Instituto Superior Tecnológico Privado IGE',
                    ],
                ],
            ],
        ];

        foreach ($gruposData as $data) {
            $grupo = Grupo::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'nombre' => $data['nombre'],
                    'descripcion' => $data['descripcion'],
                    'activo' => $data['activo'],
                ]
            );

            foreach ($data['comercios'] as $comercioData) {
                Comercio::updateOrCreate(
                    ['slug' => $comercioData['slug']],
                    [
                        'grupo_id' => $grupo->id,
                        'nombre' => $comercioData['nombre'],
                        'codigo' => $comercioData['codigo'],
                        'sigla' => $comercioData['sigla'] ?? null,
                        'color_hex' => $comercioData['color_hex'],
                        'pagina_web' => $comercioData['pagina_web'] ?? null,
                        'plataforma_carrera' => $comercioData['plataforma_carrera'] ?? null,
                        'certificado_url' => $comercioData['certificado_url'] ?? null,
                        'resolucion_revalidacion' => $comercioData['resolucion_revalidacion'] ?? null,
                        'resolucion_creacion' => $comercioData['resolucion_creacion'] ?? null,
                        'escale_minedu' => $comercioData['escale_minedu'] ?? null,
                        'link_directo_escale' => $comercioData['link_directo_escale'] ?? null,
                        'malla_curricular_url' => $comercioData['malla_curricular_url'] ?? null,
                        'catalogo_url' => $comercioData['catalogo_url'] ?? null,
                        'como_ingresar_plataforma' => $comercioData['como_ingresar_plataforma'] ?? null,
                        'reconocimiento_director' => $comercioData['reconocimiento_director'] ?? null,
                        'seminario' => $comercioData['seminario'] ?? null,
                        'convenio' => $comercioData['convenio'] ?? null,
                        'promocion_vigente' => $comercioData['promocion_vigente'] ?? null,
                        'canales_youtube' => $comercioData['canales_youtube'] ?? null,
                        'fotos' => $comercioData['fotos'] ?? null,
                        'custom_attributes' => $comercioData['custom_attributes'] ?? null,
                        'descripcion' => $comercioData['descripcion'],
                        'activo' => true,
                    ]
                );
            }
        }
    }
}
