---
deployment:
  tasks:
    - command -v composer > /home/corporacioncapsu/app_corporacion/composer_check.txt 2>&1
    - composer --version >> /home/corporacioncapsu/app_corporacion/composer_check.txt 2>&1