---
deployment:
  tasks:
    - /bin/sh -c 'node --version > /home/corporacioncapsu/app_corporacion/node_check.txt 2>&1 || true'
    - /bin/sh -c 'npm --version >> /home/corporacioncapsu/app_corporacion/node_check.txt 2>&1 || true'